# Generated by Django 3.2 on 2021-04-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veterinario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='photo',
        ),
    ]
