# Generated by Django 3.2 on 2021-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet'),
        ),
    ]
