# Generated by Django 3.2 on 2021-04-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210426_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='veterinario',
            name='photo',
        ),
    ]
