# Generated by Django 3.2 on 2021-04-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210427_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
    ]
