# Generated by Django 3.2 on 2021-04-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_pet_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinario',
            name='user',
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet'),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='veterinario',
        ),
    ]
